env:
  global:
    - TEST="TEST"
    - FREECAD_RELEASE="0.18"
    # - DEPLOY_RELEASE=${DEPLOY_RELEASE:-$FREECAD_RELEASE}
    - DEPLOY_RELEASE="0.18"
    - OSX_PORTS_CACHE=${OSX_PORTS_CACHE:-FreeCAD/FreeCAD-ports-cache}
    - DEPLOY_REPO=${DEPLOY_REPO:-FreeCAD/FreeCAD}
    - DEPLOY=${DEPLOY:-0}

os:
  - linux
  - osx

language: python

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq && sudo apt-get install -y desktop-file-utils jq zsync;
      curl -LO "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64";
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod +x jq-linux64 && sudo mv jq-linux64 $(which jq); fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install jq; fi

install:
  - eval "$(curl -fsSL "https://raw.githubusercontent.com/${OSX_PORTS_CACHE}/v${FREECAD_RELEASE}/travis-helpers.sh")"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -LO https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod a+x appimagetool-x86_64.AppImage; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash miniconda.sh -b -p $HOME/miniconda; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="$HOME/miniconda/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash miniconda.sh -b -p $HOME/miniconda; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="$HOME/miniconda/bin:$PATH"; fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd conda/linux; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash ./conda.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ..; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ls linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd conda/osx; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash ./conda.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd ..; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls osx; fi
