env:
  global:
    - FREECAD_RELEASE="0.18"
    # - DEPLOY_RELEASE=${DEPLOY_RELEASE:-$FREECAD_RELEASE}
    - DEPLOY_RELEASE="0.18"
    - RELEASE_TYPE="dev" # stable or dev
    - OSX_PORTS_CACHE=${OSX_PORTS_CACHE:-FreeCAD/FreeCAD-ports-cache}
    - DEPLOY_REPO=${DEPLOY_REPO:-FreeCAD/FreeCAD}
    - DEPLOY=${DEPLOY:-0}

os:
  - linux
  - osx

language: python
python:
  - "3.6"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq && sudo apt-get install -y desktop-file-utils jq zsync p7zip-full;
      curl -LO "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64";
      chmod +x jq-linux64 && sudo mv jq-linux64 $(which jq);
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install jq p7zip; fi

install:
  - eval "$(curl -fsSL "https://raw.githubusercontent.com/${OSX_PORTS_CACHE}/v${FREECAD_RELEASE}/travis-helpers.sh")"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      curl -LO https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage;
      wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage";
      chmod a+x appimagetool-x86_64.AppImage;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - if [ "$RELEASE_TYPE" == "stable" ]; then
      wget "https://github.com/FreeCAD/FreeCAD/releases/download/0.18/FreeCAD.0_18.Offline.Doc.7z";
      7zr x FreeCAD.0_18.Offline.Doc.7z;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd conda/linux;
      bash ./conda.sh;
      cd ..;
      ls linux;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cd conda/osx;
      bash ./conda.sh;
      cd ..;
      ls osx;
    fi
